export const LOGIN = 'LOGIN'

export const SEARCH = 'SEARCH'

export const SET_OPTION = 'SET_OPTION'

export const DOWNLOAD = 'DOWNLOAD'

export const CHANGE_USER_NAME = 'CHANGE_USER_NAME'

export const CHANGE_PASS_WORD = 'CHANGE_PASS_WORD'

export const CHANGE_DOWNLOADPATH = 'CHANGE_DOWNLOADPATH'

export const CHANGE_TIMEOUT = 'CHANGE_TIMEOUT'

export const CHANGE_PROXY = 'CHANGE_PROXY'

export const CHANGE_AUTHORID = 'CHANGE_AUTHORID'

export const CHECK_COOKIE = 'CHECK_COOKIE'

export const SELECT_PICITEM = 'SELECT_PICITEM'

export const CHANGE_PICITEM_STYLE = 'CHANGE_PICITEM_STYLE'

export const DOWNLOAD_PROGREE = 'DOWNLOAD_PROGREE'

export const LOADING_START = 'LOADING_START'
export const LOADING_END = 'LOADING_END'
