export const LOGIN = 'LOGIN'
export const LOGIN_TIMEOUT = 'LOGIN_TIMEOUT'
export const GET_USER_INFO = 'GET_USER_INFO'

export const SEARCH_PICTURE = 'SEARCH_PICTURE'
export const SEARCH_PICLICT = 'SEARCH_PICLICT'

export const SET_OPTION = 'SET_OPTION'

export const DOWNLOAD = 'DOWNLOAD'

export const CHANGE_USER_NAME = 'CHANGE_USER_NAME'

export const CHANGE_PASS_WORD = 'CHANGE_PASS_WORD'

export const CHANGE_DOWNLOADPATH = 'CHANGE_DOWNLOADPATH'

export const CHANGE_TIMEOUT = 'CHANGE_TIMEOUT'

export const CHANGE_PROXY = 'CHANGE_PROXY'

export const CHANGE_AUTHORID = 'CHANGE_AUTHORID'

export const SELECT_PICITEM = 'SELECT_PICITEM'

export const CHANGE_PICITEM_STYLE = 'CHANGE_PICITEM_STYLE'

export const CHANGE_PICITEM_PROGREE = 'CHANGE_PICITEM_PROGREE'

export const LOADING_START = 'LOADING_START'
export const LOADING_END = 'LOADING_END'
