export const LOGIN = 'LOGIN'

export const SEARCH = 'SEARCH'

export const CONFIG = 'CONFIG'

export const DOWNLOAD = 'DOWNLOAD'

export const CHANGE_USER_NAME = 'CHANGE_USER_NAME'

export const CHANGE_PASS_WORD = 'CHANGE_PASS_WORD'

export const CHANGE_DOWNLOADPATH = 'CHANGE_DOWNLOADPATH'

export const CHANGE_TIMEOUT = 'CHANGE_TIMEOUT'

export const CHANGE_PROXY = 'CHANGE_PROXY'

export const CHANGE_AUTHORID = 'CHANGE_AUTHORID'
